### PR TITLE
[DNVB] pdp #23

### PR DESCRIPTION
**Pull request by flair-chris**
This is for the PDP 
#23 

Still need to improve the logic for the additional details section

### CODE REVIEW

**Comment by flair-chris** [comment]
@flair-duncan 
The carousel was there but the design showed only tablet down so I turned it off on desktop, the slider wasn't resizing on window resize so I have added that into the main carousel.js hope that's ok.

changed the base of alternator section to need a class wrapping the containers either alternatorSection--evenBased or alternatorSection--oddBased

**Comment by flair-chris** [comment]
@flair-duncan I think the star icons might just be a local issue for you, for me if there are no ratings it displays the empty (hollow) version of the star

**Comment by flair-duncan** [comment]
@flair-chris 

Carousel still not right:
image

We need to find a way to do the resize the carousel with our own script - we are not modifying the core scripts, the only thing we can do is comment out lines

**Comment by flair-duncan** [comment]
Needs a rebase please

**Pull request merged**
